pkgs <- c(
  "assertthat",
  "backports", "base64enc", "BH", "bindr", "bindrcpp", "bookdown", "broom",
  "callr", "car", "cellranger", "cli", "clipr", "clorspace",
  "cowplot", "crayon", "curl",
  "DBI", "dbplyr", "dichromat", "digest", "dplyr",
  "evaluate",
  "forecast", "forcats", "fpp2",
  "ggplot2", "ggrepel", "glue", "gtable",
  "haven", "highr", "hms", "htmltools", "httr",
  "jsonlite",
  "knitr",
  "labeling", "lazyeval", "lubridate",
  "magrittr", "markdown", "microbenchmark", "mime", "mnormt", "modelr", "munsell",
  "NHANES",
  "openssl",
  "pillar", "pkgconfig", "plogr", "plyr", "psych", "purr",
  "R6", "RColorBrewer", "Rcpp", "readr", "readxl",
  "rematch", "reprex", "reshape2", "rlang", "rmarkdown",
  "rprojroot", "rstudioapi", "rvest",
  "scales", "selectr", "socviz", "stringi", "stringr",
  "tibble", "tidyr", "tidyselect", "tidyverse",
  "utf8",
  "viridisLite",
  "whisker",
  "xml2", "xtable",
  "yaml",
"sf","terra","spData","spDataLarge", repos = "https://nowosad.r-universe.dev")
install.packages(unique(pkgs))